# Name: Nikhil Kajrekar
# UTA ID: 1001552488

import turtle
turtle.hideturtle()
turtle.forward(100)
turtle.penup()
turtle.right(10)
turtle.forward(35)
turtle.write("East", move=False, align="right", font=("Arial", 10, "normal"))
turtle.goto(0,0)
turtle.left(190)
turtle.pendown()
turtle.forward(100)
turtle.penup()
turtle.left(10)
turtle.forward(35)
turtle.write("West", move=False, align="left", font=("Arial", 10, "normal"))
turtle.goto(0,0)
turtle.right(100)
turtle.pendown()
turtle.forward(100)
turtle.penup()
turtle.right(80)
turtle.forward(20)
turtle.write("North", move=False, align="right", font=("Arial", 10, "normal"))
turtle.goto(0,0)
turtle.right(100)
turtle.pendown()
turtle.forward(100)
turtle.penup()
turtle.right(40)
turtle.forward(20)
turtle.write("South", move=False, align="left", font=("Arial", 10, "normal"))
turtle.goto(0,-30)
turtle.left(40+90)
turtle.pendown()
turtle.circle(30)
turtle.mainloop()