# Name: Nikhil Kajrekar
# UTA ID: 1001552488

import turtle
turtle.hideturtle()
turtle.circle(50)
turtle.penup()
turtle.forward(125)
turtle.pendown()
turtle.circle(50)
turtle.penup()
turtle.forward(125)
turtle.pendown()
turtle.circle(50)
turtle.penup()
turtle.right(90)
turtle.forward(15)
turtle.right(90)
turtle.forward(15)
turtle.right(90)
turtle.forward(15)
turtle.pendown()
turtle.circle(50)
turtle.penup()
turtle.left(90)
turtle.forward(125)
turtle.right(90)
turtle.forward(6)
turtle.pendown()
turtle.circle(50)
turtle.mainloop()