# Name: Nikhil Kajrekar
# UTA ID: 1001552488

import turtle
turtle.hideturtle()
turtle.dot(10, "black")
turtle.forward(25)
turtle.penup()
turtle.forward(20)
turtle.pendown()
turtle.forward(40)
turtle.penup()
turtle.forward(20)
turtle.pendown()
turtle.forward(40)
turtle.penup()
turtle.forward(20)
turtle.pendown()
turtle.forward(25)
turtle.dot(10, "black")
turtle.right(90)
turtle.forward(190)
turtle.dot(10, "black")
turtle.right(90)
turtle.forward(25)
turtle.penup()
turtle.forward(20)
turtle.pendown()
turtle.forward(40)
turtle.penup()
turtle.forward(20)
turtle.pendown()
turtle.forward(40)
turtle.penup()
turtle.forward(20)
turtle.pendown()
turtle.forward(25)
turtle.dot(10, "black")
turtle.right(90)
turtle.forward(190)
turtle.right(135)
turtle.forward(135)
turtle.dot(10, "black")
turtle.forward(135)
turtle.left(135)
turtle.penup()
turtle.forward(190)
turtle.left(135)
turtle.pendown()
turtle.forward(135)
turtle.dot(10, "black")
turtle.forward(135)
turtle.mainloop()